// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	model "github.com/mjmhtjain/knime/src/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IOutboxMessageRepository is an autogenerated mock type for the IOutboxMessageRepository type
type IOutboxMessageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: messageEntity
func (_m *IOutboxMessageRepository) Create(messageEntity *model.OutboxMessageEntity) error {
	ret := _m.Called(messageEntity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.OutboxMessageEntity) error); ok {
		r0 = rf(messageEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadLatestPendingMessages provides a mock function with no fields
func (_m *IOutboxMessageRepository) ReadLatestPendingMessages() ([]model.OutboxMessageEntity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadLatestPendingMessages")
	}

	var r0 []model.OutboxMessageEntity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.OutboxMessageEntity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.OutboxMessageEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutboxMessageEntity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOutboxMessageRepository creates a new instance of IOutboxMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOutboxMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOutboxMessageRepository {
	mock := &IOutboxMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
