version: '3'

services:
  knime-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knime-client
    depends_on:
      - postgres
      - nats
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      NATS_URL: nats://nats:4222
      POST_MESSAGE_INTERVAL: 1
      OUTBOX_PUSH_MESSAGE_INTERVAL: 5
    volumes:
      - ./.env:/app/.env
    networks:
      - knime-network
      
  postgres:
    image: postgres:14
    container_name: knime-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - knime-network

  nats:
    image: nats:latest
    container_name: knime-nats
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
      - "6222:6222"  # Clustering port
    networks:
      - knime-network

networks:
  knime-network:
    driver: bridge

volumes:
  postgres-data: 